# vim8でdeopleteを使うのに必要
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_i = 1

# vim8でdeopleteを使うのに必要
[[plugins]]
repo = 'roxma/nvim-yarp'
on_i = 1

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = '''
  let g:go_bin_path = expand("~/go/bin")

  " goimports をfmtと同時に めちゃ便利じゃね
  let g:go_fmt_command = "goimports"
  autocmd Filetype go nmap <Leader>r <Plug>(go-run)
  autocmd Filetype go nmap <Leader>t <Plug>(go-test)

  " run :GoBuild or :GoTestCompile based on the go file
  function! s:build_go_files()
    let l:file = expand('%')
    if l:file =~# '^\f\+_test\.go$'
      call go#test#Test(0, 1)
    elseif l:file =~# '^\f\+\.go$'
      call go#cmd#Build(0)
    endif
  endfunction

  autocmd Filetype go nmap <Leader>b :<C-u>call <SID>build_go_files()<CR>
  autocmd Filetype go nmap <Leader>c <Plug>(go-coverage-toggle)
'''

# Rubyの自動補完
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']


[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
'''
on_i = 1

[[plugins]]
repo = 'vim-jp/vital.vim'

